blank_issues_enabled: false
contact_links:
  - name: Vazkii's Mods Discord
    url: https://discord.com/invite/SFrYxxD
    about: Join our Discord for support, questions, discussion.
  - name: /r/Botania
    url: https://www.reddit.com/r/botania/
    about: Visit the Botania subreddit for suggestions.
