name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open for a while with no activity. Remove stale label or comment or this will be closed soon.'
        stale-pr-message: 'This PR is stale because it has been open for a while with no activity. Remove stale label or comment or this will be closed soon.'
        exempt-pr-labels: 'confirmed,investigate'
        exempt-issue-labels: 'confirmed,investigate'
        remove-stale-when-updated: true
